// app/layout.js
import './globals.css'
import { Inter } from 'next/font/google'
import SessionWrapper from "./component/SessionWrapper" // <- fix path here

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionWrapper>{children}</SessionWrapper>
      </body>
    </html>
  )
}


// import './globals.css'
// import { Inter } from 'next/font/google'
// import SessionWrapper from './component/SessionWrapper'
// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//      <SessionWrapper>
//         <body className={inter.className}>{children}</body>
//       </SessionWrapper>
//     </html>
//   )
// } // here i wrapped body to but i only have to wrap children 
